#!/bin/bash
# Script to restart the screen sessions with cleared cache

echo "Python cache has been cleared!"
echo ""
echo "To restart your screen sessions with the new hyperparameter grids:"
echo ""
echo "=== For ramses-smd screen ==="
echo "screen -r ramses-smd"
echo "# Then run your command, example:"
echo "python run_testbed_comprehensive.py --dataset smd --parallel true"
echo ""
echo "=== For ramses-skab screen ==="
echo "screen -r ramses-skab"
echo "# Then run your command, example:"
echo "python run_testbed_comprehensive.py --dataset skab --parallel true"
echo ""
echo "=== Quick commands ==="
echo "# Resume ramses-smd:"
echo "screen -r ramses-smd"
echo ""
echo "# Resume ramses-skab:"
echo "screen -r ramses-skab"
echo ""
echo "=== Note ==="
echo "The new hyperparameter grids will now train only ONE version of each model!"
echo "This will be 3-4x faster and use 70-75% less disk space."
